CREATE TABLE "GCG_4057_WCPERF"(
 "DEPARTMENT" VARCHAR(7),
 "WORKGROUP" VARCHAR(7),
 "WORKCENTER" VARCHAR(7),
 "START_DATE" DATE,
 "ESTIMATED" NUMERIC(12,4),
 "ACTUAL" NUMERIC(12,4),
 "PRODUCTIVITY" NUMERIC(12,4),
 "RANGETYPE" VARCHAR(1),
 "BIRunID" BIGINT,
 "Beg_Date" DATE);

